### PR TITLE
Add data splits

### PR DESCRIPTION
**Pull request by radwahamedsoliman**
This adds the ability to specify the data_split per job_creation:
Tested: locally and on dog qa fleet

### CODE REVIEW

**Comment by caboteria** [comment]
My principal concern with this PR is that I'm not sure that we want the data splits column to be something that the public knows about (and can set).

**Comment by pjturcot** [comment]
I don't like this exposed to the public. I think it was @ahamino that was the advocate for including.

That puts the count at:
Yea: @ahamino 
Nay: myself, @radwahamedsoliman, @caboteria

**Comment by caboteria** [comment]
Here's a different approach that's more weakly typed so it gives up less info about the parameter names:
https://github.com/Affectiva/emotion-api-python/commit/6e2668adf2e34c4469c57626bcd0b99aefd1b742

**Comment by pjturcot** [comment]
I like that @caboteria 
We can easily leverage / pair that with some internal documentation 

How do we get that version instead? Close/remove this PR + merge yours?

**Comment by radwahamedsoliman** [comment]
I'll close this PR then so that we can go ahead with the other change ASAP

Radwa Hamed
Data Processing Engineer
[image: Inline image 1] <http://www.affectiva.com/>
[image: Facebook] <https://www.facebook.com/Affectiva/>  [image: Twitter]
<https://twitter.com/Affectiva>   [image: LinkedIn]
<https://www.linkedin.com/company-beta/722122/>  [image: Blog]
<http://www.affectiva.com/blog>

**Pull request closed without merging**
